runtime: custom
env: flex
network:
    session_affinity: true

resources:
    cpu: 4
    memory_gb: 8
    disk_size_gb: 20

readiness_check:
    app_start_timeout_sec: 22000

automatic_scaling:
    max_num_instances: 1